/**
 * Writes src/lib/blur.ts — a placeholder for every photograph, built from its
 * own colours.
 *
 *   node scripts/images/blur.mjs
 *
 * `next/image` takes `placeholder="blur"` from a static import's metadata, and
 * these photographs are served from `public/` by path, so there is no import to
 * carry one. It also accepts a data URL as the placeholder outright, which is
 * what this writes.
 *
 * Not a blurred JPEG: `sips` will not emit one under about 1.3KB whatever it is
 * asked for — a fixed header it keeps — and fifty of those is 120KB of base64
 * in the bundle to stand in for images the eye sees for half a second. An SVG
 * holding the photograph's own top and bottom colours is around 200 bytes, and
 * at the size a placeholder is actually looked at, a soft vertical wash of the
 * right colours is indistinguishable from a blurred copy.
 *
 * The colours come from a 2x2 BMP — four pixels, no decoder needed, since BMP
 * pixel data is uncompressed and the header says where it starts.
 *
 * Avatars are skipped: at 36px the placeholder is gone before it is seen.
 *
 * Re-run after adding or replacing anything in public/photos.
 */

import { execFileSync } from "node:child_process";
import { mkdtempSync, readFileSync, readdirSync, writeFileSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, "..", "..");
const photos = join(root, "public", "photos");
const out = join(root, "src", "lib", "blur.ts");

/**
 * The four pixels of a 2x2 BMP, as [r,g,b].
 *
 * A BMP is normally stored bottom row first, and says so by giving a positive
 * height; a negative height means the rows are in the order you would read them.
 * `sips` writes the negative kind. Reading the sign rather than assuming either
 * one is the difference between a gradient and the same gradient upside down —
 * which looks almost right, so it is worth not guessing.
 */
function pixels(bmp) {
  const start = bmp.readUInt32LE(10);
  const topDown = bmp.readInt32LE(22) < 0;
  const rowBytes = Math.ceil((2 * 3) / 4) * 4; // 2 pixels, 24-bit, padded to 4
  const read = (row, col) => {
    const at = start + row * rowBytes + col * 3;
    return [bmp[at + 2], bmp[at + 1], bmp[at]]; // stored BGR
  };
  const first = [read(0, 0), read(0, 1)];
  const second = [read(1, 0), read(1, 1)];
  return topDown ? { top: first, bottom: second } : { top: second, bottom: first };
}

const mix = (a, b) => a.map((v, i) => Math.round((v + b[i]) / 2));
const hex = ([r, g, b]) => "#" + [r, g, b].map((v) => v.toString(16).padStart(2, "0")).join("");

/**
 * Only what a data URL cannot carry literally.
 *
 * `encodeURIComponent` triples the length of the whole string — every space, every
 * slash, every quote — and for a 230-character SVG that is the difference between
 * 12KB across the site and 26KB. Single quotes round the attributes so the quotes
 * themselves never need escaping.
 */
const escapeSvg = (svg) =>
  svg
    .replace(/%/g, "%25")
    .replace(/#/g, "%23")
    .replace(/</g, "%3C")
    .replace(/>/g, "%3E")
    .replace(/"/g, "%22");

const work = mkdtempSync(join(tmpdir(), "blur-"));
const files = readdirSync(photos)
  .filter((f) => f.endsWith(".jpg") && !f.startsWith("avatar-"))
  .sort();

const entries = files.map((file) => {
  const small = join(work, file.replace(/\.jpg$/, ".bmp"));
  execFileSync("sips", ["-z", "2", "2", "-s", "format", "bmp", join(photos, file), "--out", small], {
    stdio: "ignore",
  });
  const { top, bottom } = pixels(readFileSync(small));
  const svg =
    `<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 1 1'>` +
    `<linearGradient id='g' x2='0' y2='1'>` +
    `<stop stop-color='${hex(mix(...top))}'/>` +
    `<stop offset='1' stop-color='${hex(mix(...bottom))}'/>` +
    `</linearGradient><rect width='1' height='1' fill='url(#g)'/></svg>`;
  return `  "/photos/${file}": "data:image/svg+xml,${escapeSvg(svg)}",`;
});
rmSync(work, { recursive: true, force: true });

writeFileSync(
  out,
  `/**
 * Generated by scripts/images/blur.mjs — do not edit.
 *
 * A placeholder per photograph: an SVG wash between the colours of its own top
 * and bottom edge, passed straight to next/image's \`placeholder\` prop. A path
 * with no entry here gets \`undefined\`, which is the same as asking for none.
 */

/**
 * The shape next/image's \`placeholder\` prop accepts for a data URL. A plain
 * \`string\` is rejected: the prop is \`"blur" | "empty" | \`data:image/\${string}\`\`,
 * and every value below starts with \`data:image/\`, so the narrower type is the
 * honest one as well as the one that compiles.
 */
type BlurPlaceholder = \`data:image/\${string}\`;

export const blurData: Record<string, BlurPlaceholder> = {
${entries.join("\n")}
};

export const blurOf = (src: string): BlurPlaceholder | undefined => blurData[src];
`,
);

console.log(`  ${files.length} placeholders → src/lib/blur.ts (${Math.round(entries.join("\n").length / 1024)}KB)`);
